
export const types = {

    uiSetUsuario : '[ui] Set Usuario',
    uiSetCatalogos : '[ui] Set Catalogos',
    uiAddNewProducto: '[ui] Add New Producto',
    uiUpdateProducto: '[ui] Update Producto',
    uiAddNewUbicacion: '[ui] Add New Ubicacion',
    uiUpdateUbicacion: '[ui] Update Ubicacion',
    uiAddNewProveedor:'[ui] Add New Proveedor',
    uiUpdateProveedor:'[ui] Update Proveedor',
    uiOpenModal: '[ui] Open Modal',
    uiCloseModal: '[ui] Close Modal',
    uiClearDataLogout: '[ui] Clear Data Logout',
    uiViewModalSurtir : '[ui] View Modal Surtir',
    uiSetLoading : '[ui] Set Loading',
    uiAddPedido : '[ui] Add Pedido',
    uiRemovePedido : '[ui] Remove Pedido',
    uiUpdatePedido : '[ui] Update Pedido',
    uiSetResumenCosto : '[ui] Set Resumen Costo',
    
    authLogin : '[ui] Login',
    authSetUsuarios : '[auth] Set Usuarios',
    authNewUsuario  : '[auth] New Usuario',
    authSaveEditUsuario : '[auth] Save Edit Usuario',
    authEditUsuario : '[auth] Edit Usuario',
    authChekingFinish : '[auth] Cheking Finish',
    autLogOut : '[auth] LogoOut',

    entradaList : '[entrada] Entrada List',
    entradaListFilter: '[entrada] Entrada List Filter',
    entradaEdit : '[entrada] Entrada Edit',
    entradaEmpyEdit : '[entrada] Entrada Empy Edit',
    entradaUpdate : '[entrada] Entrada Update',
    entradaDelete : '[entrada] Delete',
    entradaClearLists : '[entrada] Clear Lists',
    entradaEditCabecero : '[entrada] Edit Cabecero',
    entradaEditDetalle : '[entrada] Edit Detalle',
    entradaClearDetalle : '[entrada] Clear Detalle',
    entradaAddDetalle : '[entrada] Add Detalle',
    entradaUpdateDetalle : '[entrada] Update Detalle',
    entradaDeleteDetalle : '[entrada] Delete Detalle',
    
    surtidoClearProductos : '[surtido] Clear Productos',
    surtidoDeleteProductoSolicitud: '[surtido] Delete Solicitud',
    surtidoFillProductoSolicitud:'[surtido] Fill Producto Solicitud',
    surtidoAddProductoSolicitud: '[surtido] Add Solicitud',

    surtidoUpdatePorcentajeSolicitud:'[surtido] Update Porcentaje Solicitud',
    surtidoAddProductoSurtido:'[surtido] Add Producto Surtido',
    surtidoListaProductosSurtidos: '[surtido] Lista Productos Surtido',
    surtidoListaFilterProductosSurtidos: '[surtido] Filter Lista Productos Surtidos',
    surtidoDeleteProdcutosSurtido: '[surtido] Lista Delete Productos Surtido',

    remisionesListPedidos : '[remisiones] List Pedidos',
    remisionesCancelListPedidos : '[remisiones] Cancel List Pedidos',
    remisionesGetRemision : '[remisiones] Get Remision',
    remisionClearData : '[remisiones] Clear Data',
    remisionGetListRemisiones: '[remisiones] Get List Remisiones',
    remisionesUpdateTotalAbono: '[remisiones] Update Total Abonos',

    farmaciaSetListEntradas : '[farmacia] Set List Entradas',
}